tag_prefix = "v"
from_latest_tag = true
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
  "echo {{version}}",
]
post_bump_hooks = []

[commit_types]
hotfix = { changelog_title = "Hotfixes" }
release = { changelog_title = "Releases" }

[changelog]
path = "docs/CHANGELOG.md"
authors = []

[bump_profiles]

