name: Release

on:
  push:
    branches: ["main"]
    paths:
      - "build/version"

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'release(version):')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set output variables
        id: vars
        run: |
          version="$(cat ./build/version)"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./docs/LATEST_CHANGELOG.md
          tag_name: ${{ steps.vars.outputs.version }}
