name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        env:
          APP_ENV: ci
          BUCKET_NAME: bucket_name
          ACCOUNT_ID: r2_account_id
          ACCESS_KEY_ID: r2_access_key_id
          SECRET_ACCESS_KEY: r2_secret_access_key
        run: cargo test --verbose
